In [1]:
import pandas as pd
from pandas import DataFrame
import numpy as np

In [2]:
df = pd.read_excel(r'C:\Users\EDZ\Desktop\汉星\excel-pdf\016.xlsx',keep_default_na=False)
df['数量'] = df['数量'].astype('int64')
df['单价'] = df['单价'].astype('int64')
df['金额'] = df['金额'].astype('int64')
df['已核销'] = df['已核销'].astype('int64')
df['未核销'] = df['未核销'].astype('int64')
df['运单号'] = [i.split('-')[-1] for i in df['运单号']]
df.index = range(2,len(df.index)+2)
df.drop(index=list(df[df['费用'] == '主单费'].index), inplace=True)
del_list = []
for i in range(0,len(df.index)-1):
    for j in range(i+1,len(df.index)):
        if df.loc[df.index[i],'订单号']==df.loc[df.index[j],'订单号'] and df.loc[df.index[i],'运单号']==df.loc[df.index[j],'运单号'] and df.loc[df.index[i],'航程']==df.loc[df.index[j],'航程'] and df.loc[df.index[i],'数量']==df.loc[df.index[j],'数量'] and df.loc[df.index[i],'费用']==df.loc[df.index[j],'费用']:
            print(df.index[i],df.index[j])
            df.loc[df.index[i],'单价'] += df.loc[df.index[j],'单价']
            df.loc[df.index[i],'金额'] += df.loc[df.index[j],'金额']
            df.loc[df.index[i],'已核销'] += df.loc[df.index[j],'已核销']
            df.loc[df.index[i],'未核销'] += df.loc[df.index[j],'未核销']
            df.loc[df.index[i],'附加说明'] = df.loc[df.index[i],'附加说明'] if df.loc[df.index[i],'附加说明']!='' else df.loc[df.index[j],'附加说明']
            del_list.append(df.index[j])

df.drop(index=del_list,inplace=True)
df.to_excel(r'C:\Users\EDZ\Desktop\汉星\excel-pdf\副本-016.xlsx')

9 10
21 22
31 32
38 39
69 71
78 79
91 92
95 96
106 107
109 110

In [14]:
df = pd.read_excel(r'C:\Users\EDZ\Desktop\汉星\制单费\202012制单费-远航原表.xlsx')
df

,总单号,分单号,运抵报告发送时间,是否已入海关库,放行件数,放行重量,运抵件数,运抵重量,操作员账号,回执内容,回执时间,报关编号,放行时间,代理人,航班号,保存时间
0,016-54483424,2170,2020-12-19 09:55:17,已入海关库,30.0,525.0,30,525,PVGLC01,45201 空运出口运抵报告传输成功。比对结果为：运抵正常。,2020-12-19 09:56:50,2.233202e+17,2020-12-19 09:58:22,HSS,858,2020-12-19 09:55:13
1,016-54483435,1948,2020-12-19 09:55:22,已入海关库,42.0,735.0,42,735,PVGLC01,45201 空运出口运抵报告传输成功。比对结果为：运抵正常。,2020-12-19 09:57:15,2.233202e+17,2020-12-19 09:58:22,HSS,858,2020-12-19 09:55:20
2,016-54483446,2239,2020-12-20 14:45:29,已入海关库,110.0,1870.0,110,1870,PVGLC01,45201 空运出口运抵报告传输成功。比对结果为：运抵正常。,2020-12-20 14:47:02,2.233202e+17,2020-12-20 14:47:53,HSS,199,2020-12-20 14:45:25
3,016-55952002,2427,2020-12-12 16:13:53,已入海关库,250.0,4375.0,250,4375,PVGLC01,45201 空运出口运抵报告传输成功。比对结果为：运抵正常。,2020-12-12 16:15:55,2.233202e+17,2020-12-12 16:16:02,HSS,858,2020-12-12 16:13:49
4,016-55952013,2246,2020-12-13 10:33:55,已入海关库,90.0,1575.0,90,1575,PVGLC01,45201 空运出口运抵报告传输成功。比对结果为：运抵正常。,2020-12-13 10:36:03,2.233202e+17,2020-12-13 10:35:48,HSS,858,2020-12-13 10:33:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,016-62380581,8456,2020-12-11 11:28:11,已入海关库,75.0,1275.0,75,1275,PVGLC01,45201 空运出口运抵报告传输成功。比对结果为：运抵正常。,2020-12-11 11:29:59,2.233202e+17,2020-12-11 11:30:05,HSS,858,2020-12-11 11:28:11
115,016-62380592,9952,2020-12-11 11:28:22,已入海关库,84.0,1428.0,84,1428,PVGLC01,45201 空运出口运抵报告传输成功。比对结果为：运抵正常。,2020-12-11 11:30:15,2.233202e+17,2020-12-11 11:30:04,HSS,261,2020-12-11 11:28:18
116,016-62508714,SSHA5296643,2020-12-26 13:33:21,已入海关库,6.0,2430.0,6,2430,PVGLC01,45201 空运出口运抵报告传输成功。比对结果为：运抵正常。,2020-12-26 13:47:50,2.358202e+17,2020-12-26 13:47:26,HSS,836,2020-12-26 13:33:18
117,016-62508935,052344,2020-12-29 16:11:05,已入海关库,6.0,3618.0,6,3618,PVGLC01,45201 空运出口运抵报告传输成功。比对结果为：运抵正常。,2020-12-29 16:12:50,2.233202e+17,2020-12-29 16:14:39,HSS,671,2020-12-29 16:11:03
118,016-91776565,0217,2020-12-16 14:36:28,已入海关库,1.0,221.0,1,221,PVGLC01,45201 空运出口运抵报告传输成功。比对结果为：运抵正常。,2020-12-16 14:38:33,2.233202e+17,2020-12-16 14:39:23,HSS,858,2020-12-16 14:36:23

In [28]:
df = df[['总单号']]
df.insert(1,'counts',1)
df

              总单号  counts
0    016-54483424       1
1    016-54483435       1
2    016-54483446       1
3    016-55952002       1
4    016-55952013       1
..            ...     ...
114  016-62380581       1
115  016-62380592       1
116  016-62508714       1
117  016-62508935       1
118  016-91776565       1

[119 rows x 2 columns]

In [30]:
df = df.groupby('总单号').count().reset_index()

In [31]:
for i in df.index:
    print(df.loc[i,'总单号'],df.loc[i,'counts'])

016-54483424 1
016-54483435 1
016-54483446 1
016-55952002 1
016-55952013 1
016-55952024 1
016-55952035 1
016-55952046 1
016-55952050 1
016-55952061 1
016-55952072 1
016-55952083 1
016-55952094 1
016-55952105 1
016-55952116 1
016-55952120 1
016-55952131 1
016-55952142 1
016-55952153 1
016-55952164 1
016-55952175 1
016-55952186 1
016-55952190 1
016-55952201 1
016-55952212 1
016-55952223 1
016-55952234 1
016-55952245 1
016-55952256 1
016-55952260 1
016-55952271 1
016-55952282 1
016-55952293 1
016-55952304 1
016-55952315 1
016-55952326 1
016-55952330 1
016-55952341 1
016-55952352 1
016-55952363 4
016-55952374 1
016-55952385 1
016-55952400 3
016-55952411 1
016-55952433 1
016-55952444 1
016-55952455 1
016-55952470 1
016-55952481 1
016-55952492 1
016-55952503 1
016-55954802 1
016-55954846 1
016-62195556 1
016-62195560 1
016-62195571 1
016-62195582 1
016-62195593 1
016-62195604 1
016-62195615 1
016-62195626 1
016-62195630 1
016-62195641 1
016-62195652 1
016-62195663 1
016-62195674 1
016-62195685 1
016-62195696 1
016-62195700 1
016-62195711 1
016-62195766 1
016-62195770 1
016-62195781 1
016-62195792 1
016-62195803 1
016-62195814 2
016-62195825 1
016-62195836 1
016-62195840 1
016-62195851 1
016-62195862 1
016-62195873 1
016-62195884 1
016-62195895 1
016-62195906 1
016-62195910 1
016-62195932 1
016-62195954 1
016-62195976 1
016-62195980 1
016-62195991 1
016-62196002 1
016-62196013 1
016-62196024 1
016-62196035 1
016-62196046 5
016-62196050 1
016-62196061 1
016-62196072 1
016-62379343 1
016-62379354 1
016-62379365 1
016-62379590 1
016-62380566 1
016-62380581 1
016-62380592 1
016-62508714 1
016-62508935 1
016-91776565 1

In [33]:
df.insert(1,'金额',df['counts']*5)

ValueError: cannot insert 金额, already exists

In [35]:
for i in df.index:
    print(df.loc[i,'总单号'],df.loc[i,'金额'])

016-54483424 5
016-54483435 5
016-54483446 5
016-55952002 5
016-55952013 5
016-55952024 5
016-55952035 5
016-55952046 5
016-55952050 5
016-55952061 5
016-55952072 5
016-55952083 5
016-55952094 5
016-55952105 5
016-55952116 5
016-55952120 5
016-55952131 5
016-55952142 5
016-55952153 5
016-55952164 5
016-55952175 5
016-55952186 5
016-55952190 5
016-55952201 5
016-55952212 5
016-55952223 5
016-55952234 5
016-55952245 5
016-55952256 5
016-55952260 5
016-55952271 5
016-55952282 5
016-55952293 5
016-55952304 5
016-55952315 5
016-55952326 5
016-55952330 5
016-55952341 5
016-55952352 5
016-55952363 20
016-55952374 5
016-55952385 5
016-55952400 15
016-55952411 5
016-55952433 5
016-55952444 5
016-55952455 5
016-55952470 5
016-55952481 5
016-55952492 5
016-55952503 5
016-55954802 5
016-55954846 5
016-62195556 5
016-62195560 5
016-62195571 5
016-62195582 5
016-62195593 5
016-62195604 5
016-62195615 5
016-62195626 5
016-62195630 5
016-62195641 5
016-62195652 5
016-62195663 5
016-62195674 5
016-62195685 5
016-62195696 5
016-62195700 5
016-62195711 5
016-62195766 5
016-62195770 5
016-62195781 5
016-62195792 5
016-62195803 5
016-62195814 10
016-62195825 5
016-62195836 5
016-62195840 5
016-62195851 5
016-62195862 5
016-62195873 5
016-62195884 5
016-62195895 5
016-62195906 5
016-62195910 5
016-62195932 5
016-62195954 5
016-62195976 5
016-62195980 5
016-62195991 5
016-62196002 5
016-62196013 5
016-62196024 5
016-62196035 5
016-62196046 25
016-62196050 5
016-62196061 5
016-62196072 5
016-62379343 5
016-62379354 5
016-62379365 5
016-62379590 5
016-62380566 5
016-62380581 5
016-62380592 5
016-62508714 5
016-62508935 5
016-91776565 5

In [31]:
df = pd.read_excel(r'C:\Users\EDZ\Desktop\汉星\excel-excel\机场\202011仓储费-机场货运站.xlsx')
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Agency Charges Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Customer,AL,Flight,Flt Date,AOO/AOD,Pre,Awb,Pcs,GrWt,ChWt,Goods,Charge,Amount,Currency,X Rate,Amount RMB,Inv No.
4,NaN,BLF,CA,195,03/Nov/2020,TPE,999,79649522,14,2363,2363,CONSOL,2. Export Warehouse Use (International Cargo),945.2,RMB,1,945.2,T12021788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,NaN,BLF,CA,1091,27/Nov/2020,TPE,999,79648170,6,1756,1756,CONSOL,Export Warehouse Use (International Cargo) T3,702.4,RMB,1,702.4,T30018773
331,NaN,BLF,CA,1091,27/Nov/2020,TPE,999,79648181,2,1059,1059,CONSOL,Export Warehouse Use (International Cargo) T3,423.6,RMB,1,423.6,T30018773
332,NaN,BLF,CA,1053,28/Nov/2020,ORD,999,79649651,4,572,572,CONSOL,Export Warehouse Use (International Cargo) T3,228.8,RMB,1,228.8,T30018773
333,NaN,BLF,CA,1091,27/Nov/2020,TPE,999,79648203,1,35,100,7 8 DIMETHOXY 3 3,Export Warehouse Use (International Cargo) T3,14,RMB,1,14,T30018773
334,NaN,BLF,CA,1029,29/Nov/2020,JFK,999,10308421,1,602,602,CONSOL,Export Warehouse Use (International Cargo) T3,240.8,RMB,1,240.8,T30018773

In [37]:
df = pd.read_excel(r'C:\Users\EDZ\Desktop\汉星\excel-excel\机场\202011仓储费-机场货运站.xlsx')
df.dropna(axis=0,thresh=17,inplace=True)
df.dropna(axis=1,inplace=True)
df.columns = df.iloc[0].values
df.drop(index=[df.iloc[0].name],inplace=True)
df.insert(1,'运单号',df['Pre']+'-'+df['Awb'])
df

,Customer,运单号,AL,Flight,Flt Date,AOO/AOD,Pre,Awb,Pcs,GrWt,ChWt,Goods,Charge,Amount,Currency,X Rate,Amount RMB,Inv No.
4,BLF,999-79649522,CA,195,03/Nov/2020,TPE,999,79649522,14,2363,2363,CONSOL,2. Export Warehouse Use (International Cargo),945.2,RMB,1,945.2,T12021788
5,BLF,999-79649500,CA,3071,03/Nov/2020,TPE,999,79649500,11,131,131,CONSOL,2. Export Warehouse Use (International Cargo),52.4,RMB,1,52.4,T12021788
6,BLF,999-79649426,CA,3071,03/Nov/2020,TPE,999,79649426,1,111,111,CONSOL,2. Export Warehouse Use (International Cargo),44.4,RMB,1,44.4,T12021788
7,BLF,999-79649452,CA,3071,03/Nov/2020,TPE,999,79649452,2,211,211,CONSOL,2. Export Warehouse Use (International Cargo),84.4,RMB,1,84.4,T12021788
8,BLF,999-79649430,CA,3071,03/Nov/2020,TPE,999,79649430,5,1359,1359,CONSOL,2. Export Warehouse Use (International Cargo),543.6,RMB,1,543.6,T12021788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,BLF,999-79648170,CA,1091,27/Nov/2020,TPE,999,79648170,6,1756,1756,CONSOL,Export Warehouse Use (International Cargo) T3,702.4,RMB,1,702.4,T30018773
331,BLF,999-79648181,CA,1091,27/Nov/2020,TPE,999,79648181,2,1059,1059,CONSOL,Export Warehouse Use (International Cargo) T3,423.6,RMB,1,423.6,T30018773
332,BLF,999-79649651,CA,1053,28/Nov/2020,ORD,999,79649651,4,572,572,CONSOL,Export Warehouse Use (International Cargo) T3,228.8,RMB,1,228.8,T30018773
333,BLF,999-79648203,CA,1091,27/Nov/2020,TPE,999,79648203,1,35,100,7 8 DIMETHOXY 3 3,Export Warehouse Use (International Cargo) T3,14,RMB,1,14,T30018773
334,BLF,999-10308421,CA,1029,29/Nov/2020,JFK,999,10308421,1,602,602,CONSOL,Export Warehouse Use (International Cargo) T3,240.8,RMB,1,240.8,T30018773

In [43]:
df = pd.read_excel(r'C:\Users\EDZ\Desktop\汉星\excel-excel\机场\202011仓储费-CCSP.xlsx')
'机场货运' in df['结算单位'].values

False

In [50]:
df = pd.read_excel(r'C:\Users\EDZ\Desktop\汉星\制单费\机场货运\202011制单费-机场货运站.xlsx')
df = df[['总单号','备注']]
df.insert(1, 'counts', 1)
df = df.groupby(['总单号','备注']).count().reset_index()
# df.insert(1, '金额', df['counts'] * 5)
# df.to_excel(os.path.split(file_path)[0] + '/' + '处理的机场货运制单费表格.xlsx')
df

             总单号  备注  counts
0    16033088790  T3       1
1    40313535012  T3       1
2    40681575690  T3       2
3    40681575701  T3       1
4    40681575712  T3       1
..           ...  ..     ...
335  99979650981  T3       1
336  99979651003  T3       1
337  99979657071  T3       1
338  99979687731  T3       1
339  99979716744  T3       1

[340 rows x 3 columns]

In [51]:
''.join('123-1234'.split('-'))

'1231234'

In [7]:
df = pd.read_excel(r'‪C:\Users\EDZ\Desktop\RY576\发票装箱单合同\RY576 20210104100742.xlsx')
df

OSError: [Errno 22] Invalid argument: '\u202aC:\\Users\\EDZ\\Desktop\\RY576\\发票装箱单合同\\RY576 20210104100742.xlsx'